# Minecraft Pipes Datapack - Website Configuration
# A beautiful, modern website for the Minecraft Pipes datapack

title: Minecraft Pipes
description: "Advanced pipe system for item transportation in Minecraft - inspired by classic Tekkit pipes but implemented as a modern datapack"
baseurl: ""
url: "https://minecraft-pipes.com"

# Author information
author:
  name: "Minecraft Pipes Team"
  email: "contact@minecraft-pipes.com"
  bio: "Creating amazing Minecraft datapacks"
  location: "Minecraft Universe"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/minecraft-pipes"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/minecraft-pipes"

# Social media
social:
  github: minecraft-pipes
  twitter: minecraft_pipes
  discord: minecraft-pipes

# Site settings
lang: en_US
timezone: UTC
encoding: utf-8

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
      sidebar: "docs"
      topnav: "docs"
      comments: false
      search: true
      breadcrumbs: true
      toc: true
      toc_sticky: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# SEO
google_analytics: ""
google_analytics_universal: ""

# Search
search_full_content: true
search_tokenizer_separator: /[\s/]+/

# Theme settings
theme_settings:
  # Meta
  meta:
    keywords: "minecraft, datapack, pipes, item transportation, redstone, automation"
    description: "Advanced pipe system for item transportation in Minecraft"
  
  # Header
  header:
    image: "/assets/images/header-bg.jpg"
    image_description: "Minecraft Pipes Header"
    overlay_filter: 0.5
    actions:
      - label: "Get Started"
        url: "/docs/installation/"
        icon: "fas fa-download"
        class: "btn--primary"
      - label: "View on GitHub"
        url: "https://github.com/minecraft-pipes"
        icon: "fab fa-github"
        class: "btn--secondary"
  
  # Navigation
  navigation:
    main:
      - title: "Home"
        url: "/"
      - title: "Documentation"
        url: "/docs/"
      - title: "Features"
        url: "/docs/features/"
      - title: "Installation"
        url: "/docs/installation/"
      - title: "Tutorials"
        url: "/docs/tutorials/"
      - title: "API Reference"
        url: "/docs/api/"
      - title: "Examples"
        url: "/docs/examples/"
      - title: "Support"
        url: "/docs/support/"
  
  # Footer
  footer:
    links:
      - title: "Documentation"
        links:
          - label: "Getting Started"
            url: "/docs/installation/"
          - label: "Features"
            url: "/docs/features/"
          - label: "API Reference"
            url: "/docs/api/"
          - label: "Examples"
            url: "/docs/examples/"
      - title: "Community"
        links:
          - label: "GitHub"
            url: "https://github.com/minecraft-pipes"
          - label: "Discord"
            url: "https://discord.gg/minecraft-pipes"
          - label: "Issues"
            url: "https://github.com/minecraft-pipes/issues"
          - label: "Discussions"
            url: "https://github.com/minecraft-pipes/discussions"
      - title: "Resources"
        links:
          - label: "Download"
            url: "/docs/installation/"
          - label: "Changelog"
            url: "/docs/changelog/"
          - label: "License"
            url: "/docs/license/"
          - label: "Privacy"
            url: "/docs/privacy/"
  
  # Sidebar
  sidebar:
    nav:
      - title: "Getting Started"
        children:
          - title: "Installation"
            url: /docs/installation/
          - title: "Quick Start"
            url: /docs/quick-start/
          - title: "Basic Usage"
            url: /docs/basic-usage/
      - title: "Features"
        children:
          - title: "Pipe Types"
            url: /docs/features/pipe-types/
          - title: "Item Transportation"
            url: /docs/features/item-transportation/
          - title: "Redstone Control"
            url: /docs/features/redstone-control/
          - title: "Crafting System"
            url: /docs/features/crafting/
      - title: "Advanced"
        children:
          - title: "Configuration"
            url: /docs/advanced/configuration/
          - title: "Performance"
            url: /docs/advanced/performance/
          - title: "Troubleshooting"
            url: /docs/advanced/troubleshooting/
      - title: "API Reference"
        children:
          - title: "Functions"
            url: /docs/api/functions/
          - title: "Commands"
            url: /docs/api/commands/
          - title: "Variables"
            url: /docs/api/variables/
      - title: "Examples"
        children:
          - title: "Basic Setup"
            url: /docs/examples/basic-setup/
          - title: "Complex Networks"
            url: /docs/examples/complex-networks/
          - title: "Redstone Automation"
            url: /docs/examples/redstone-automation/

# Color scheme
color_scheme: "light"

# Typography
typography: "system"

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "minecraft-pipes"

# Search
search: true
search_full_content: true

# Breadcrumbs
breadcrumbs: true

# Table of contents
toc: true
toc_sticky: true

# Sidebar
sidebar:
  nav: "docs"

# GitHub
github:
  repository_url: "https://github.com/minecraft-pipes/minecraft-pipes"
  repository_name: "minecraft-pipes"
  branch: "main"
  path: "docs"

# Edit on GitHub
edit_on_github: true
edit_on_github_text: "Edit this page on GitHub"
edit_on_github_branch: "main"

# Last modified
last_modified_at: true

# Reading time
reading_time: true

# Related posts
related: true

# Share buttons
share: true

# Social sharing
social-share: true

# Newsletter
newsletter:
  title: "Stay Updated"
  description: "Get the latest updates about Minecraft Pipes"
  button_text: "Subscribe"
  placeholder: "Enter your email"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: ""
    anonymize_ip: true

# Ads
ads:
  google:
    client: ""
    slot: ""

# Search
search:
  provider: "lunr"
  path: "/search.json"
  field_match: ["title", "excerpt", "categories", "tags", "url"]

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - Page :num"
  limit: 0
  trail: {}

# Feed
feed:
  path: atom.xml
  limit: 10

# Sitemap
sitemap:
  path: sitemap.xml
  lastmod: true
  changefreq: weekly
  priority: 0.5
  exclude: []

# Robots
robots:
  user_agent: "*"
  disallow:
    - /admin/
    - /private/
  sitemap: "/sitemap.xml"

# Security headers
security_headers:
  X-Frame-Options: DENY
  X-XSS-Protection: "1; mode=block"
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# Performance
performance:
  compress_html: true
  minify_css: true
  minify_js: true
  inline_css: false
  inline_js: false

# Development
development:
  url: "http://localhost:4000"
  port: 4000
  host: "127.0.0.1"
  baseurl: ""
  assets_dir: "assets"
  images_dir: "assets/images"
  css_dir: "assets/css"
  js_dir: "assets/js"
  fonts_dir: "assets/fonts"
