title: Minecraft Pipes
description: Advanced pipe system for item transportation between containers in Minecraft
baseurl: ""
url: "https://minecraft-pipes.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Site settings
author:
  name: Minecraft Pipes Team
  email: support@minecraft-pipes.com

# Social links
social:
  github: aaron777collins/MinecraftPipes
  twitter: minecraft_pipes
  discord: minecraft-pipes

# Navigation
nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation/
  - title: Basic Usage
    url: /basic-usage/
  - title: Advanced Features
    url: /advanced-features/
  - title: Configuration
    url: /configuration/
  - title: API Reference
    url: /api-reference/
  - title: Troubleshooting
    url: /troubleshooting/

# Footer links
footer_links:
  - title: GitHub
    url: https://github.com/aaron777collins/MinecraftPipes
  - title: Issues
    url: https://github.com/aaron777collins/MinecraftPipes/issues
  - title: Discussions
    url: https://github.com/aaron777collins/MinecraftPipes/discussions
  - title: Releases
    url: https://github.com/aaron777collins/MinecraftPipes/releases

# Custom CSS and JS
head_scripts:
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js

# Custom styling
custom_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css
  - /assets/css/custom.css

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Additional settings for better performance
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# SEO settings
lang: en_US
timezone: UTC
