title: Minecraft Pipes System
description: A comprehensive pipe system for Minecraft that allows item transportation between containers
baseurl: ""
url: "https://minecraft-pipes.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme settings - using a custom theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
author:
  name: Minecraft Pipes Team
  email: support@minecraft-pipes.com

# Social links
social:
  github: minecraft-pipes
  twitter: minecraft_pipes
  discord: minecraft-pipes

# Navigation
nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation/
  - title: Basic Usage
    url: /basic-usage/
  - title: Advanced Features
    url: /advanced-features/
  - title: Configuration
    url: /configuration/
  - title: API Reference
    url: /api-reference/
  - title: Troubleshooting
    url: /troubleshooting/

# Footer links
footer_links:
  - title: GitHub
    url: https://github.com/minecraft-pipes/minecraft-pipes
  - title: Issues
    url: https://github.com/minecraft-pipes/minecraft-pipes/issues
  - title: Discussions
    url: https://github.com/minecraft-pipes/minecraft-pipes/discussions
  - title: Releases
    url: https://github.com/minecraft-pipes/minecraft-pipes/releases

# Custom CSS and JS
head_scripts:
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js

# Custom styling
custom_css:
  - /assets/css/custom.css
  - https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css
