name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MDL
      run: |
        pip install minecraft-datapack-language
        
    - name: Install zip
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        
    - name: Run build script
      run: |
        ./scripts/build.sh
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minecraft-pipes-build
        path: |
          dist/pipes_datapack.zip
          dist/pipes_resource_pack.zip
          dist/pipes_complete.zip
          dist/README.md
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/pipes_datapack.zip
          dist/pipes_resource_pack.zip
          dist/pipes_complete.zip
          dist/README.md
        body_path: dist/README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release (Manual)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/pipes_datapack.zip
          dist/pipes_resource_pack.zip
          dist/pipes_complete.zip
          dist/README.md
        body_path: dist/README.md
        draft: true
        prerelease: false
        tag_name: v${{ github.run_number }}
        name: Build ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
