name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    name: build & test (${{ matrix.os }} / py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install MDL
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install minecraft-datapack-language

      - name: Check syntax
        shell: bash
        run: |
          mdl check src/

      - name: Build datapack
        shell: bash
        run: |
          mdl build --mdl . -o dist --wrapper minecraft_pipes --pack-format 48

      - name: Verify build output
        shell: bash
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/minecraft_pipes/
          
          # Check for required files
          if [[ -f "dist/minecraft_pipes/pack.mcmeta" ]]; then
            echo "✅ pack.mcmeta found"
          else
            echo "❌ pack.mcmeta missing"
            exit 1
          fi
          
          if [[ -d "dist/minecraft_pipes/data" ]]; then
            echo "✅ data directory found"
          else
            echo "❌ data directory missing"
            exit 1
          fi
          
          if [[ -d "dist/minecraft_pipes/data/pipes" ]]; then
            echo "✅ pipes namespace found"
          else
            echo "❌ pipes namespace missing"
            exit 1
          fi

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*
          if-no-files-found: error
