name: Deploy Documentation

on:
  push:
    branches: [ master ]
    paths: [ 'docs/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'docs/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd docs
        bundle install
        
    - name: Build site
      run: |
        cd docs
        bundle exec jekyll build
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        cname: minecraft-pipes.github.io
        
    - name: Build preview
      if: github.event_name == 'pull_request'
      run: |
        cd docs
        bundle exec jekyll build --baseurl "/${{ github.repository }}"
        
    - name: Upload preview
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: docs/_site/
