name: Test Examples

on:
  push:
    branches: [ master, main ]
    paths: [ 'test_examples/**', '.github/workflows/test-examples.yml', '*.mdl' ]
  pull_request:
    branches: [ master, main ]
    paths: [ 'test_examples/**', '.github/workflows/test-examples.yml', '*.mdl' ]

jobs:
  test-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MDL
      run: |
        python -m pip install --upgrade pip
        python -m pip install minecraft-datapack-language
        
    - name: Test main datapack compilation
      run: |
        echo "Testing main datapack compilation..."
        
        # Test syntax check
        mdl check src/
        
        # Test build
        mdl build --mdl src -o test_examples/dist --wrapper minecraft_pipes --pack-format 82
        
        # Verify basic structure
        if [[ -f "test_examples/dist/minecraft_pipes/pack.mcmeta" ]]; then
          echo "✅ pack.mcmeta found"
        else
          echo "❌ pack.mcmeta missing"
          exit 1
        fi
        
        if [[ -d "test_examples/dist/minecraft_pipes/data/pipes" ]]; then
          echo "✅ pipes namespace found"
        else
          echo "❌ pipes namespace missing"
          exit 1
        fi
        
        echo "✅ Main datapack compiles successfully!"
        
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-datapacks
        path: test_examples/dist/
        retention-days: 7
