name: Test Examples

on:
  push:
    branches: [ master, main ]
    paths: [ 'test_examples/**', '.github/workflows/test-examples.yml', '*.mdl' ]
  pull_request:
    branches: [ master, main ]
    paths: [ 'test_examples/**', '.github/workflows/test-examples.yml', '*.mdl' ]

jobs:
  test-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pipx
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install MDL via pipx
      run: |
        pipx install minecraft-datapack-language
        
    - name: Verify MDL installation
      run: |
        mdl --help
        mdl --version || echo "Version command not available"
        
    - name: Test main datapack
      run: |
        echo "Testing main Minecraft Pipes datapack..."
        
        # Test syntax check
        mdl check .
        
        # Test build
        mdl build --mdl . -o test_examples/dist --wrapper minecraft_pipes --pack-format 48
        
        echo "Main datapack test complete!"
        
    - name: Test individual MDL files
      run: |
        echo "Testing individual MDL files..."
        
        # Test each MDL file individually (excluding example files that aren't standalone)
        for file in *.mdl; do
          if [[ -f "$file" ]] && [[ "$file" != "example_usage.mdl" ]]; then
            echo "Testing $file"
            mdl check "$file"
          fi
        done
        
        echo "Individual MDL files test complete!"
        
    - name: Test example datapacks
      run: |
        echo "Testing example datapacks..."
        
        # Create test examples directory if it doesn't exist
        mkdir -p test_examples
        
        # Test each example MDL file
        for file in test_examples/*.mdl; do
          if [[ -f "$file" ]]; then
            echo "Testing example: $file"
            mdl check "$file"
            mdl build --mdl "$file" -o test_examples/dist
          fi
        done
        
        # Test multi-file example projects
        for dir in test_examples/*/; do
          if [[ -d "$dir" ]] && [[ -f "$dir"/*.mdl ]]; then
            echo "Testing multi-file project: $dir"
            mdl check "$dir"
            mdl build --mdl "$dir" -o test_examples/dist
          fi
        done
        
        echo "Example datapacks test complete!"
        
    - name: Test Python API examples
      run: |
        echo "Testing Python API examples..."
        
        # Test Python examples if they exist
        for file in test_examples/*.py; do
          if [[ -f "$file" ]] && [[ "$(basename "$file")" != "run_all_tests.py" ]]; then
            echo "Testing Python example: $file"
            python "$file"
          fi
        done
        
        echo "Python API examples test complete!"
        
    - name: Verify generated datapacks
      run: |
        echo "Verifying generated datapacks..."
        ls -la test_examples/dist/ || echo "No dist directory found"
        
        # Check that datapacks have the expected structure
        for dir in test_examples/dist/*/; do
          if [[ -d "$dir" ]] && [[ "$(basename "$dir")" != "data" ]]; then
            echo "Checking datapack: $dir"
            ls -la "$dir"
            
            # Check for pack.mcmeta
            if [[ -f "$dir/pack.mcmeta" ]]; then
              echo "✅ pack.mcmeta found in $dir"
            else
              echo "❌ pack.mcmeta missing in $dir"
              exit 1
            fi
            
            # Check for data directory
            if [[ -d "$dir/data" ]]; then
              echo "✅ data directory found in $dir"
            else
              echo "❌ data directory missing in $dir"
              exit 1
            fi
          fi
        done
        
    - name: Test CLI commands
      run: |
        echo "Testing CLI commands..."
        
        # Test help
        mdl --help
        
        # Test new command
        mdl new cli_test --name "CLI Test" --pack-format 48
        
        # Verify created project
        ls -la cli_test/
        cat cli_test/*.mdl
        
        # Test check and build
        mdl check cli_test/
        mdl build --mdl cli_test/ -o test_examples/dist
        
        # Clean up
        rm -rf cli_test/
        
    - name: Test pipe functionality
      run: |
        echo "Testing pipe functionality..."
        
        # Build the main datapack
        mdl build --mdl . -o test_examples/dist --wrapper minecraft_pipes --pack-format 48
        
        # Check for required functions
        if [[ -f "test_examples/dist/minecraft_pipes/data/pipes/function/init.mcfunction" ]]; then
          echo "✅ init function found"
        else
          echo "❌ init function missing"
          exit 1
        fi
        
        if [[ -f "test_examples/dist/minecraft_pipes/data/pipes/function/tick_main.mcfunction" ]]; then
          echo "✅ tick_main function found"
        else
          echo "❌ tick_main function missing"
          exit 1
        fi
        
        if [[ -f "test_examples/dist/minecraft_pipes/data/pipes/function/create_source.mcfunction" ]]; then
          echo "✅ create_source function found"
        else
          echo "❌ create_source function missing"
          exit 1
        fi
        
        if [[ -f "test_examples/dist/minecraft_pipes/data/pipes/function/create_sink.mcfunction" ]]; then
          echo "✅ create_sink function found"
        else
          echo "❌ create_sink function missing"
          exit 1
        fi
        
        echo "Pipe functionality test complete!"
        
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-datapacks
        path: test_examples/dist/
        retention-days: 7
